In [104]:
import pandas as pd
import numpy as np

In [106]:
Model = pd.read_csv("use.csv")

In [107]:
Model

,ModerateModerateModerateModerateModerateModerateModerateModerateModerate,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,MH005,,92.838327,29.193691,24.774936,52.03000,13.039869,1.320000,14.835094,26.498063,105.42483,Moderate
1,MH005,PM2.7,92.838327,29.193691,24.774936,54.21612,13.039869,1.280000,14.835094,26.498063,105.42483,Moderate
2,MH005,PM2.8,92.838327,29.193691,24.774936,54.21612,13.039869,0.693924,14.835094,26.498063,105.42483,Moderate
3,MH005,PM2.9,92.838327,29.193691,24.774936,56.06000,13.039869,1.440000,14.835094,26.498063,105.42483,Moderate
4,MH005,PM2.10,92.838327,29.193691,24.774936,42.79000,13.039869,0.693924,14.835094,26.498063,105.42483,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...
2351,MH005,PM2.2357,124.420000,117.480000,24.774936,118.22000,1.050000,0.370000,14.835094,4.520000,138.00000,Moderate
2352,MH009,PM2.2358,83.580000,109.450000,2.650000,110.55000,0.770000,0.290000,14.835094,4.700000,105.42483,Moderate
2353,MH009,PM2.2359,66.570000,109.690000,3.040000,112.28000,13.039869,0.300000,14.835094,26.498063,132.00000,Moderate
2354,MH009,PM2.2360,17.610000,91.270000,4.630000,95.88000,0.590000,0.693924,14.835094,4.340000,125.00000,Moderate
2355,MH009,PM2.2361,11.810000,97.490000,2.380000,99.88000,13.039869,0.693924,14.835094,4.560000,116.00000,Moderate

In [108]:
Model_1 = Model.drop("ModerateModerateModerateModerateModerateModerateModerateModerateModerate",axis="columns")

In [109]:
Model_1

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,AQI,AQI_Bucket
0,,92.838327,29.193691,24.774936,52.03000,13.039869,1.320000,14.835094,26.498063,105.42483,Moderate
1,PM2.7,92.838327,29.193691,24.774936,54.21612,13.039869,1.280000,14.835094,26.498063,105.42483,Moderate
2,PM2.8,92.838327,29.193691,24.774936,54.21612,13.039869,0.693924,14.835094,26.498063,105.42483,Moderate
3,PM2.9,92.838327,29.193691,24.774936,56.06000,13.039869,1.440000,14.835094,26.498063,105.42483,Moderate
4,PM2.10,92.838327,29.193691,24.774936,42.79000,13.039869,0.693924,14.835094,26.498063,105.42483,Moderate
...,...,...,...,...,...,...,...,...,...,...,...
2351,PM2.2357,124.420000,117.480000,24.774936,118.22000,1.050000,0.370000,14.835094,4.520000,138.00000,Moderate
2352,PM2.2358,83.580000,109.450000,2.650000,110.55000,0.770000,0.290000,14.835094,4.700000,105.42483,Moderate
2353,PM2.2359,66.570000,109.690000,3.040000,112.28000,13.039869,0.300000,14.835094,26.498063,132.00000,Moderate
2354,PM2.2360,17.610000,91.270000,4.630000,95.88000,0.590000,0.693924,14.835094,4.340000,125.00000,Moderate
2355,PM2.2361,11.810000,97.490000,2.380000,99.88000,13.039869,0.693924,14.835094,4.560000,116.00000,Moderate

In [182]:
AQI = Model_1.drop([" PM2.5","AQI_Bucket"],axis="columns")
AQI

,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,AQI
0,92.838327,29.193691,24.774936,52.03000,13.039869,1.320000,14.835094,26.498063,105.42483
1,92.838327,29.193691,24.774936,54.21612,13.039869,1.280000,14.835094,26.498063,105.42483
2,92.838327,29.193691,24.774936,54.21612,13.039869,0.693924,14.835094,26.498063,105.42483
3,92.838327,29.193691,24.774936,56.06000,13.039869,1.440000,14.835094,26.498063,105.42483
4,92.838327,29.193691,24.774936,42.79000,13.039869,0.693924,14.835094,26.498063,105.42483
...,...,...,...,...,...,...,...,...,...
2351,124.420000,117.480000,24.774936,118.22000,1.050000,0.370000,14.835094,4.520000,138.00000
2352,83.580000,109.450000,2.650000,110.55000,0.770000,0.290000,14.835094,4.700000,105.42483
2353,66.570000,109.690000,3.040000,112.28000,13.039869,0.300000,14.835094,26.498063,132.00000
2354,17.610000,91.270000,4.630000,95.88000,0.590000,0.693924,14.835094,4.340000,125.00000
2355,11.810000,97.490000,2.380000,99.88000,13.039869,0.693924,14.835094,4.560000,116.00000

In [183]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [184]:
X= AQI[["PM10","NH3",'NO' ,'NO2','NOx','CO','SO2','O3']]
y=AQI[['AQI']]

In [185]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.1)

In [186]:
lr = LinearRegression()

In [187]:
lr.fit(X_train, y_train)

LinearRegression()

In [188]:
y_pred= lr.predict(X_test)
y_pred

array([[ 52.00409426],
       [ 74.98304425],
       [ 51.82899294],
       [ 51.04471307],
       [ 82.86330569],
       [171.73817557],
       [176.42624579],
       [153.3215259 ],
       [ 71.18931449],
       [125.88179519],
       [225.73352837],
       [ 74.0281838 ],
       [ 60.99244895],
       [104.67347904],
       [ 85.48184662],
       [147.32293102],
       [130.58888902],
       [132.93612731],
       [102.40495226],
       [101.42677808],
       [168.4487501 ],
       [176.40999142],
       [119.38242643],
       [191.67443836],
       [106.56068519],
       [130.0474446 ],
       [249.20190963],
       [ 79.8840824 ],
       [ 68.05127561],
       [202.49373027],
       [ 72.70235356],
       [104.67027594],
       [101.71287751],
       [123.67804626],
       [131.43873993],
       [207.50522544],
       [110.72831413],
       [154.38387746],
       [ 77.22820358],
       [ 81.73195002],
       [123.37322869],
       [201.59891489],
       [ 68.74743687],
       [104.67027594],
       [ 72.39665429],
       [ 92.44059868],
       [ 89.24825107],
       [ 96.94317648],
       [ 98.86116751],
       [152.21192953],
       [115.57348596],
       [ 82.49989025],
       [236.23358459],
       [ 56.09857113],
       [101.85133175],
       [ 85.17803487],
       [ 79.22693864],
       [ 89.40037127],
       [115.34023872],
       [114.92273959],
       [ 97.43847585],
       [115.7958498 ],
       [104.98670244],
       [239.82386662],
       [ 94.34625895],
       [104.67027594],
       [ 50.34381306],
       [241.87505866],
       [ 75.66154993],
       [106.03545195],
       [105.45659009],
       [195.46003193],
       [105.98442822],
       [113.77557518],
       [ 73.158167  ],
       [119.4168239 ],
       [210.56860024],
       [ 80.11384658],
       [ 67.44935203],
       [123.63903208],
       [ 92.40368497],
       [104.67027594],
       [148.64921929],
       [ 91.64281927],
       [ 73.36833728],
       [180.2275056 ],
       [184.6154511 ],
       [ 87.93200474],
       [ 91.97855523],
       [ 52.79446266],
       [119.70077212],
       [ 49.87683769],
       [ 90.07219994],
       [151.85394088],
       [ 51.52862019],
       [108.68213426],
       [115.56261012],
       [ 84.2531921 ],
       [ 82.92759397],
       [ 92.01662078],
       [104.67027594],
       [ 57.01562328],
       [ 72.65947593],
       [ 79.39775474],
       [ 90.39878019],
       [ 83.18156066],
       [130.08711154],
       [ 60.03209941],
       [ 50.51789286],
       [ 85.20942934],
       [145.88217377],
       [ 90.42703619],
       [ 64.36908564],
       [151.83508252],
       [199.26852236],
       [210.61456184],
       [111.0562812 ],
       [ 75.78073144],
       [ 81.14026766],
       [119.72697762],
       [ 43.51552546],
       [145.06555515],
       [ 79.77851841],
       [192.63260556],
       [ 53.82134165],
       [162.27428791],
       [ 80.27730581],
       [125.24367549],
       [ 95.51777907],
       [103.34873106],
       [ 91.38670557],
       [ 87.99953434],
       [ 68.46867916],
       [104.67027594],
       [110.80573485],
       [ 76.17664804],
       [ 93.49908954],
       [101.41653685],
       [104.41697213],
       [ 81.82705516],
       [127.99774998],
       [ 95.43652231],
       [ 74.39518319],
       [114.07382419],
       [124.54979535],
       [195.42955644],
       [ 98.04121756],
       [129.25888411],
       [153.81077346],
       [ 69.33315721],
       [ 98.19117827],
       [104.67027594],
       [116.23871855],
       [143.52752587],
       [113.79219786],
       [ 42.43541731],
       [105.34728533],
       [ 70.09027491],
       [112.30607324],
       [ 84.00072775],
       [184.0988679 ],
       [ 53.20427884],
       [ 75.29004973],
       [106.9549189 ],
       [ 88.05583065],
       [137.29520479],
       [108.01318645],
       [ 56.68273667],
       [ 58.70028797],
       [ 96.47435715],
       [ 80.7339277 ],
       [229.75392579],
       [201.89137352],
       [ 83.83757197],
       [176.86026392],
       [206.03753251],
       [ 57.48481865],
       [164.15580034],
       [119.6737476 ],
       [161.03632741],
       [235.46764612],
       [ 80.24089609],
       [104.67027594],
       [ 66.25860183],
       [ 76.01597116],
       [ 39.96257716],
       [104.67027594],
       [204.11738809],
       [ 61.64809444],
       [102.91640728],
       [ 94.14014624],
       [ 87.38147445],
       [131.29298467],
       [ 88.16309995],
       [ 71.92127739],
       [196.89642737],
       [118.14770984],
       [ 94.54732679],
       [172.32857458],
       [ 91.29708227],
       [133.01760888],
       [155.68426597],
       [ 60.53273362],
       [ 65.82726789],
       [185.43343327],
       [ 85.86815067],
       [114.75793249],
       [149.28708133],
       [105.6227831 ],
       [138.59941391],
       [ 66.05092416],
       [ 50.4914661 ],
       [107.95660181],
       [ 80.82136803],
       [115.13352209],
       [138.02563831],
       [141.16671625],
       [237.13346971],
       [ 54.63911555],
       [176.30432965],
       [117.37641983],
       [115.87240595],
       [104.67027594],
       [ 46.11766592],
       [ 41.50400793],
       [133.31103585],
       [125.91367405],
       [ 56.62261857],
       [119.17179161],
       [ 94.66845696],
       [ 42.64202206],
       [167.56804322],
       [104.7035589 ],
       [103.24769636],
       [ 60.21103703],
       [ 93.98256652]])

In [1]:
lr.score(X_test, y_test)

NameError: name 'lr' is not defined