In [1]:
import pandas as pd
import numpy as np

In [2]:
Model = pd.read_csv("hawaman.csv")
Model

      Sr.No  SO2  NOx  RSPM  AQI
0         1   36   76   185  157
1         2   46   81   143  129
2         3   36   80   183  155
3         4   40   72   191  161
4         5   20   69   147  131
...     ...  ...  ...   ...  ...
3203    269   17   25   165  143
3204    270   17   34   272  222
3205    271   19   38   153  135
3206    272   12   48    72   72
3207    273   26   35   128  119

[3208 rows x 5 columns]

In [3]:
Model_1 = Model.drop("Sr.No",axis="columns")
Model_1

      SO2  NOx  RSPM  AQI
0      36   76   185  157
1      46   81   143  129
2      36   80   183  155
3      40   72   191  161
4      20   69   147  131
...   ...  ...   ...  ...
3203   17   25   165  143
3204   17   34   272  222
3205   19   38   153  135
3206   12   48    72   72
3207   26   35   128  119

[3208 rows x 4 columns]

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [5]:
X= Model_1[["SO2","NOx",'RSPM' ]]
y=Model_1[['AQI']]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.1)

In [7]:
lr = LinearRegression()

In [8]:
lr.fit(X_train, y_train)

LinearRegression()

In [9]:
y_pred= lr.predict(X_test)
y_pred

array([[ 89.05917693],
       [ 78.17669617],
       [233.20678183],
       [ 56.24187776],
       [133.3487313 ],
       [132.30256005],
       [241.48205378],
       [156.86272162],
       [137.84879432],
       [ 64.32096533],
       [ 45.08099285],
       [112.0474202 ],
       [ 72.41608513],
       [ 87.02770477],
       [132.81084572],
       [ 65.677573  ],
       [208.13078858],
       [132.78217969],
       [120.90849037],
       [ 85.22154747],
       [ 44.81811932],
       [ 87.4530347 ],
       [223.97458192],
       [113.54194066],
       [264.78292512],
       [103.44463103],
       [ 70.71473392],
       [148.16516208],
       [105.61065539],
       [ 60.01419055],
       [106.38055681],
       [ 62.47315845],
       [ 62.30306718],
       [ 69.55591817],
       [217.54086013],
       [ 52.09413579],
       [ 57.7564955 ],
       [193.11855399],
       [179.22123093],
       [ 76.59825459],
       [118.47824585],
       [ 58.43361466],
       [193.18255553],
       [228.09245743],
       [149.51153047],
       [ 57.61831616],
       [198.60971087],
       [ 66.11609568],
       [ 63.69164412],
       [ 92.59052389],
       [162.48307635],
       [ 49.74248954],
       [254.37509024],
       [ 54.06046898],
       [ 77.34142073],
       [224.07669543],
       [ 50.47260913],
       [175.26557676],
       [113.44465472],
       [263.15376362],
       [135.96454035],
       [112.63500297],
       [110.6566201 ],
       [138.75242876],
       [ 83.61800965],
       [ 58.96594234],
       [ 66.45651326],
       [ 95.66149783],
       [ 86.66315634],
       [187.76736101],
       [ 48.48097615],
       [ 38.63779361],
       [123.99572525],
       [ 86.67535222],
       [127.02809193],
       [151.37373055],
       [ 99.30882403],
       [126.74418724],
       [192.00709757],
       [235.47404249],
       [239.61844972],
       [197.29496199],
       [ 88.45922057],
       [156.31372024],
       [ 54.71327957],
       [ 78.14019173],
       [168.94391467],
       [ 72.11211465],
       [145.28861382],
       [156.23737662],
       [134.36729075],
       [198.69015105],
       [133.8358396 ],
       [184.90011814],
       [ 83.81024366],
       [ 52.48179234],
       [ 65.60819127],
       [146.5478467 ],
       [163.36775658],
       [153.08151619],
       [ 81.64369184],
       [ 65.79027485],
       [ 48.26665675],
       [ 74.27717363],
       [ 87.81869471],
       [207.41473827],
       [ 83.09197019],
       [130.20939836],
       [ 58.54631651],
       [ 59.59248776],
       [108.61403214],
       [158.94374477],
       [178.89453357],
       [153.88675311],
       [ 80.56908961],
       [111.13141218],
       [173.52587921],
       [102.18297144],
       [ 54.12777375],
       [ 60.09720365],
       [ 89.76057314],
       [193.43691767],
       [ 89.29885348],
       [ 66.5116795 ],
       [173.02987826],
       [125.47378121],
       [112.97199696],
       [122.10179096],
       [ 62.93595819],
       [131.88395695],
       [ 59.50628613],
       [146.18566763],
       [106.88319573],
       [ 55.61015568],
       [218.74150317],
       [107.76386825],
       [219.12152487],
       [ 64.83170922],
       [219.76872021],
       [183.18021983],
       [ 60.66945936],
       [159.61202864],
       [203.81368567],
       [139.90670935],
       [113.50692905],
       [ 84.41774602],
       [140.70548035],
       [188.10801364],
       [221.37685055],
       [ 77.2221956 ],
       [ 59.54264437],
       [112.89120702],
       [ 49.47183496],
       [105.05276137],
       [ 77.42747616],
       [201.5236401 ],
       [113.80616081],
       [156.78216673],
       [ 52.8807109 ],
       [106.48770076],
       [136.18757469],
       [ 46.38670289],
       [ 95.18307861],
       [ 87.91162317],
       [ 84.13688367],
       [120.09111492],
       [118.47824585],
       [123.75952965],
       [215.22837941],
       [238.04111972],
       [199.98252214],
       [158.73817181],
       [ 73.27765724],
       [ 52.15930625],
       [ 99.65447561],
       [148.67543586],
       [ 43.38429151],
       [ 67.03739506],
       [146.25964188],
       [ 46.50815118],
       [109.39384893],
       [ 51.37615472],
       [ 55.38928714],
       [134.50403462],
       [123.27932587],
       [ 59.15381888],
       [125.48837795],
       [ 93.72155015],
       [130.12120862],
       [ 45.2765616 ],
       [120.11659241],
       [ 61.60500571],
       [ 75.05699042],
       [199.8634432 ],
       [ 77.11853259],
       [110.15611549],
       [244.80042797],
       [219.15454837],
       [157.91415837],
       [ 93.75703186],
       [195.9206894 ],
       [ 62.55713692],
       [ 76.69200223],
       [204.5653632 ],
       [ 63.13819642],
       [188.51210884],
       [ 73.00352171],
       [ 83.77040448],
       [ 68.47236595],
       [ 97.69276643],
       [ 97.83544945],
       [ 64.75314244],
       [111.95226857],
       [ 28.63864645],
       [173.11947199],
       [ 54.20388232],
       [106.52865152],
       [184.10163955],
       [ 51.35410082],
       [ 63.7313371 ],
       [206.72629977],
       [155.00134072],
       [ 80.1182822 ],
       [183.46629033],
       [ 78.24046265],
       [ 37.29127902],
       [124.63101712],
       [ 57.0433042 ],
       [ 96.16867192],
       [228.40154789],
       [103.05469396],
       [141.90293485],
       [149.25102631],
       [ 96.43792252],
       [118.51934281],
       [129.36005364],
       [ 93.32745917],
       [125.75444001],
       [105.58193201],
       [125.65609985],
       [110.99124472],
       [ 52.72044616],
       [160.15807653],
       [ 50.75215636],
       [ 46.7965022 ],
       [ 90.57148267],
       [ 47.1654081 ],
       [ 78.97947488],
       [136.07042652],
       [ 70.36817433],
       [260.30699296],
       [ 49.12942928],
       [133.92321017],
       [ 53.99085219],
       [113.98818705],
       [ 65.03912409],
       [131.04017013],
       [103.83886822],
       [162.27449255],
       [191.95014677],
       [178.05060054],
       [143.84259012],
       [ 62.86672266],
       [ 48.65551373],
       [ 82.6733671 ],
       [218.82074292],
       [137.09334344],
       [195.1280611 ],
       [ 50.46714008],
       [106.67689243],
       [ 40.40402289],
       [ 85.38312734],
       [ 46.21980017],
       [ 40.17098432],
       [142.37448103],
       [ 61.42935655],
       [133.37309721],
       [163.46726568],
       [174.53554602],
       [148.97118668],
       [123.41484345],
       [164.30248376],
       [121.05769666],
       [ 90.16370297],
       [128.36015599],
       [234.0096179 ],
       [148.29430258],
       [148.38805022],
       [170.81632252],
       [229.27408959],
       [147.31751306],
       [160.23945059],
       [119.49782804],
       [ 85.71117133],
       [ 80.44550701],
       [134.34737116],
       [132.64154214],
       [238.68638431],
       [ 79.79357295],
       [ 45.63546328],
       [111.95010276],
       [ 99.42374905],
       [117.63475143],
       [ 67.26949974],
       [105.19442165],
       [135.57910695],
       [108.98864215],
       [133.76288808],
       [104.86942   ],
       [131.51645503],
       [161.90965171],
       [145.26974846],
       [ 88.36895387],
       [ 87.12373292],
       [ 89.62332768],
       [116.22166239],
       [ 67.35783569],
       [ 59.90830438],
       [102.50124626],
       [ 94.14688008],
       [ 98.24399097]])

In [10]:
lr.score(X_test, y_test)

0.9404561155947192

In [11]:
import pickle

In [12]:
data = {"model":lr}
with open('Hawaman_pred.pkl','wb') as file:
    pickle.dump(data,file)

In [13]:
with open('Hawaman_pred.pkl','rb') as file:
    data= pickle.load(file)
    model = data["model"]